# Generated by Django 4.2.6 on 2023-10-06 17:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawl_Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_ID', models.CharField(default=uuid.uuid4, editable=False, max_length=32)),
                ('name', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='ongoing', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Crawl_Obj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=400)),
                ('response_code', models.IntegerField()),
                ('content_tag', models.CharField(max_length=20)),
                ('tag_attributes', models.CharField(max_length=400)),
                ('crawled_data', models.CharField(max_length=20000)),
                ('crawl_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objs', to='crawler_api.crawl_job')),
            ],
        ),
    ]
