# Generated by Django 4.2.5 on 2023-10-07 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crawl_Obj',
        ),
    ]
